name: "Chromatic"

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1 # required as chromatic won't work with shallow clone

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: Build storybook
        run: npm run build-storybook
        working-directory: ./packages/visualizations-react

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: 338d0576bcf1 # ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: ./packages/visualizations-react/storybook-static
